using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BotChallenge.Runner.CodeRunners.Models.GameActions
{
    /// <summary>
    /// Represents interface for all action handlers. It must apply to field new step generated by user code 
    /// </summary>
    internal interface IActionHandler
    {
        Field ApplyStep(string[] stepParams, Field field);
    }
}
