using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BotChallenge.LanguageCompiler.Exceptions
{
    /// <summary>
    /// Base class for all exceptions generated by compiler.
    /// </summary>
    public class CompilerException : Exception
    {
        public CompilerException() : base() { }
        public CompilerException(string message) : base(message) { }

    }
}
